### ISSUE TITLE
ecr: secret not being generated

### ISSUE THREAD

**Issue by vdice** [deis/registry-token-refresher#11]
When setting up values for using ECR as the off-cluster registry option, a sample snippet of Workflow's global `values.yaml` would look something like:
```
...
registry-token-refresher:
...
  ecr:
    # Your AWS access key. Leave it empty if you want to use IAM credentials.
    accesskey: "ACCESS_KEY"
    # Your AWS secret key. Leave it empty if you want to use IAM credentials.
    secretkey: "SECRET_KEY"
    # Any S3 region
    region: "us-west-2"
    registryid: "myregistryid"
    hostname: "myhostname.amazonaws.com"
...
```
Yet, when the `registryid` and `hostname` values are non-empty as above, it seems a bug is hit and the necessary `private-registry-ecr` secret is not created correctly.  When an attempt to build/deploy an example app, the following is hit:
```
Error running git receive hook [error getting private registry details secrets "private-registry-ecr" not found]`
```

Meanwhile, counterintuitively, if both `registryid` and `hostname` are just kept at `""` then the aforementioned secret is created properly and build/deploys work as intended.
